### ISSUE TITLE
Private suite type fails to run in Xcode

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-testing#524] opened 2024-07-06 14:22 UTC
### Description

Using `private` access level modifier on a test `@Suite` will make the tests silently fail to run.
I assume it's because `private` will make the type disappear from some compiled code so swift-testing's `Suite`-detection mechanism fails to detect the `Suite`.

### Expected behavior

```swift
@Suite private struct MyTestSuite {
    @Test func shouldFail() throws {
        let _ = try #require(Optional<Bool>.none)
    }
}
```
Should error like `Cannot use 'private' access level modifier on a test 'Suite'`.

### Actual behavior

```swift
@Suite private struct MyTestSuite {
    @Test func shouldFail() throws {
        let _ = try #require(Optional<Bool>.none)
    }
}
```
Silently doesn't run the tests:
```bash
Test Suite 'Selected tests' started at 2024-07-06 17:45:23.006.
Test Suite 'MyTests.xctest' started at 2024-07-06 17:45:23.006.
Test Suite 'MyTests.xctest' passed at 2024-07-06 17:45:23.006.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' passed at 2024-07-06 17:45:23.007.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Program ended with exit code: 0
```

### Steps to reproduce

Try to run the code described above.

### swift-testing version/commit hash

The one bundled with the Swift version below.

### Swift & OS version (output of `swift --version ; uname -a`)

```bash
swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx15.0
Darwin ---.local 24.0.0 Darwin Kernel Version 24.0.0: ---; root:xnu-11215.0.115.501.3~1/RELEASE_ARM64_T6000 arm64
```

**Comment by grynspan** [comment] 2024-07-06 16:37
Suites marked private are valid. If they are failing to compile and run, that's the bug, not that the keyword is allowed.

**Comment by grynspan** [comment] 2024-07-06 16:54
I am not able to reproduce this issue at my desk when I run `swift test --enable-swift-testing`. I do see the test fail to run within Xcode. Xcode builds test targets differently than Swift Package Manager, so this looks to me like an Xcode-specific issue.

Do you see the issue when you run `swift test --enable-swift-testing` on your package?

**Comment by grynspan** [comment] 2024-07-06 23:58
Tracked internally at Apple as rdar://131227159.

**Comment by MahdiBM** [comment] 2024-07-07 09:22
Hmm you're right. Even in Xcode it works fine when running all tests (Command+U), but if you click on the UI button next to the `@Suite` type declaration, it silently fails to run the test suite.
The same behavior does not happen with `@Test` functions.

Considering this is an Xcode problem, feel free to close this issue if you want.

**Comment by MahdiBM** [comment] 2024-07-07 09:38
Actually:

```bash
 !  ~ swift test --enable-swift-testing --filter MyTestSuite
Building for debugging...
[3/3] Linking MyLibPackageTests.swift-testing
Build complete! (1.09s)
􀟈  Test run started.
􀄵  Testing Library Version: 75.9 (arm64e-apple-macos13.0)
􀟈  Suite MyTestSuite started.
􀟈  Test shouldFail() started.
􀢄  Test shouldFail() recorded an issue at ParsedTypeTests.swift:9:21: Expectation failed: Optional<Bool>.none → nil → nil
􀢄  Test shouldFail() failed after 0.001 seconds with 1 issue.
􀢄  Suite MyTestSuite failed after 0.001 seconds with 1 issue.
􀢄  Test run with 1 test failed after 0.001 seconds with 1 issue.
Building for debugging...
[3/3] Linking MyLibPackageTests
Build complete! (1.04s)
warning: No matching test cases were run
Test Suite 'Selected tests' started at 2024-07-07 13:03:27.353.
Test Suite 'MyLibPackageTests.xctest' started at 2024-07-07 13:03:27.354.
Test Suite 'MyLibPackageTests.xctest' passed at 2024-07-07 13:03:27.354.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' passed at 2024-07-07 13:03:27.354.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
 !  ~ swift test --enable-swift-testing
Building for debugging...
[3/3] Linking MyLibPackageTests.swift-testing
Build complete! (1.08s)
􀟈  Test run started.
􀄵  Testing Library Version: 75.9 (arm64e-apple-macos13.0)
􀟈  Suite MyTestSuite started.
􀟈  Suite SecondTestSuite started.
􀟈  Test shouldFail() started.
􀟈  Test shouldFail() started.
􀢄  Test shouldFail() recorded an issue at ParsedTypeTests.swift:9:21: Expectation failed: Optional<Bool>.none → nil → nil
􀢄  Test shouldFail() recorded an issue at ParsedTypeTests.swift:15:21: Expectation failed: Optional<Bool>.none → nil → nil
􀢄  Test shouldFail() failed after 0.001 seconds with 1 issue.
􀢄  Test shouldFail() failed after 0.001 seconds with 1 issue.
􀢄  Suite MyTestSuite failed after 0.001 seconds with 1 issue.
􀢄  Suite SecondTestSuite failed after 0.001 seconds with 1 issue.
􀢄  Test run with 2 tests failed after 0.001 seconds with 2 issues.
Building for debugging...
[3/3] Linking MyLibPackageTests
Build complete! (1.05s)
Test Suite 'All tests' started at 2024-07-07 13:03:44.658.
Test Suite 'All tests' passed at 2024-07-07 13:03:44.659.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
```

So it appears everything is fine when running `swift test --enable-swift-testing`, but if you run `swift test --enable-swift-testing --filter MyTestSuite`, things start to get interesting.
As you can see, the tests are run before the build logs complete, and there is also a `warning: No matching test cases were run` log emitted.

**Comment by grynspan** [comment] 2024-07-07 11:47
No, still an Xcode bug. You're misinterpreting the log output. As of right now, SwiftPM builds test targets twice—once per testing library. The logging you're seeing about building is for the second build. This is all temporary infrastructure that will change when Swift Testing is added to the Swift 6 toolchain.

**Comment by grynspan** [comment] 2024-07-07 11:48
Closing this GitHub issue as the problem is Xcode-specific. Apple is tracking it internally.

**Closed by grynspan** 2024-07-07 11:48 UTC
Labels: bug

**Comment by MahdiBM** [comment] 2024-07-07 11:53
Ah you're right. I see it now.
