### ISSUE TITLE
Crash when running an arguments test when parallel tests are enabled

### ISSUE THREAD

**Issue by noremac** [apple/swift-testing#565] opened 2024-07-22 13:55 UTC
### Description

I have written a stripped down reproduction case that more reliably-than-not produces a crash when run.

### Expected behavior

I would expect this test to run successfully without crashing.

### Actual behavior

The test (usually) crashes with the following error:

```
XCTest/HarnessEventHandler.swift:303: Fatal error: Internal inconsistency: No test reporter for test case argumentIDs: nil in test MyLibraryTests.FooTests/equal(lhs:rhs:)/MyLibraryTests.swift:17:4
```

### Steps to reproduce

1. Make a new swift package and use swift testing as the testing system.
2. Paste the following in to a test.
3. Ensure parallel tests are enabled.
4. Run the suite.

For me it crashes more often than not.

```swift
import Testing

struct Foo: Equatable, ExpressibleByIntegerLiteral, ExpressibleByStringLiteral {
  let value: String

  init(stringLiteral value: String) {
    self.value = value
  }

  init(integerLiteral value: Int) {
    self.value = String(value)
  }
}

@Suite
struct FooTests {
  @Test(arguments: [
    ("1" as Foo, "1" as Foo),
    (1, 1),
    (2, 2),
    (3, 3),
  ])
  func equal(lhs: Foo, rhs: Foo) {
    #expect(lhs == rhs)
  }
}
```

### swift-testing version/commit hash

Xcode 16.0 beta 3 (16A5202i)

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx15.0
Darwin Studio.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Jul  1 21:58:14 PDT 2024; root:xnu-11215.0.132.501.1~1/RELEASE_ARM64_T6000 arm64

**Comment by grynspan** [comment] 2024-07-22 14:04
Duplicate of #480

**Closed by grynspan** 2024-07-22 14:04 UTC
Labels: bug
