### ISSUE TITLE
class setUp/tearDown equivalents in swift-testing

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-testing#225] opened 2024-02-18 08:03 UTC
### Description

For normal `func setUp` and `func tearDown` we can convert them to `init` and `deinit` call on our test `class` according to the [doc](https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing/migratingfromxctest#Converting-setUp-and-tearDown-functions) here.

But what are the equivalents for `class func setUp` and `class func tearDown` here?

```swift
class TestCaseBase: XCTestCase {    
    override class func setUp() {
        // Class level init code
		print("[C] setup")
    }
    
    override class func tearDown() {
		// Class level deinit code
		print("[C] tearDown")
    }

    override func setUp() {
        // instance level init code
		...
		print("[I] setup")
    }
    
    override func tearDown() {
		// instance level deinit code
		...
		print("[I] tearDown")
    }
	
	func testMethod1() {}
	func testMethod2() {}
}
```

We'll get
```
[C] setup
[I] setup
[I] tearDown
[I] setup
[I] tearDown
[C] tearDown
```

After converting to `swift-testing`

```swift
@Suite
class TestCaseBase {
	// 🚧
   	class func setUp() {
        // Class level init code
		print("[C] setup")
    }
    
	// 🚧	
   	class func tearDown() {
		// Class level deinit code
		print("[C] tearDown")
    }

	init() {
        // instance level init code
		...
		print("[I] setup")
	}

    deinit {
		// instance level deinit code
		...
		print("[I] tearDown")
    }
	
	@Test 
	func method1() {}
	@Test
	func method2() {}
}
```

We'll get
```
[I] setup
[I] tearDown
[I] setup
[I] tearDown
```

### Expected behavior

Get the equivalents behavior of `XCTest`

### Actual behavior

Missing class level setUp and tearDown code.

### Workaround

```swift
// Track it manually with `Bool` value to workaround class level setUp
```swift
@Suite
class AttributeTestBase {
    
    static var hasClassSetUp = false
    static var hasClassTearDown = false
    
    init() {
        if !Self.hasClassSetUp { // Ignore thread safety issues for now 🤔
            Self.setUp()
            Self.hasClassSetUp = true
        }
    }
    
    deinit {
        ...
    }
    
    class func setUp() { ... }
    
    class func tearDown() { ... }
}
final class ATest: TestBase {
	init() {
		super.init()
        // instance level init code
		...
		print("[I] setup")
	}

	deinit {
		// instance level deinit code
		...
		print("[I] tearDown")
	}

	@Test
	func method1() { ... }
	@Test
	func method2() { ... }
}
```

### swift-testing version/commit hash

0.3.0

**Comment by stmontgomery** [comment] 2024-02-18 12:50
Thank you, yes this is missing functionality we intend to add. I have explored this some so assigning to myself for now.

**Comment by stmontgomery** [comment] 2024-02-18 12:52
Duplicate of #36

**Closed** 2024-02-18 12:54 UTC
Labels: enhancement, public-api
