### ISSUE TITLE
Compile error when building with 6.0-DEVELOPMENT-SNAPSHOT-2024-06-18-a

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-testing#496] opened 2024-06-19 17:09 UTC
### Description

I get the following error when compiling 
```
Stored property 'xcTestCompatibleSelector' of 'Sendable'-conforming struct 'Test' has non-sendable type '__XCTestCompatibleSelector?' (aka 'Optional<Selector>')
```

### Expected behavior

It compiles

### swift-testing version/commit hash

0.10.0

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: x86_64-apple-macosx14.0
Darwin Adams-iMac-Pro-2.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64

**Comment by stmontgomery** [comment] 2024-06-19 17:35
Dupe of #491

See my [comment](https://github.com/apple/swift-testing/issues/491#issuecomment-2175986139) there

**Comment by stmontgomery** [comment] 2024-06-19 17:38
Duplicate of #491

See my [comment](https://github.com/apple/swift-testing/issues/491#issuecomment-2175986139) there

**Closed** 2024-06-19 17:38 UTC
Labels: bug
