### ISSUE TITLE
Add WASI support

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-testing#228] opened 2024-02-18 14:42 UTC
### Description

Current this build will fail due to some upstream blocked.

Open this issue to track the support for WASI

```
// ubuntu20 + swiftwasm 5.9.1 https://github.com/swiftwasm/swift
swift test --triple wasm32-unknown-wasi
<unknown>:0: warning: glibc not found for 'wasm32-unknown-wasi'; C stdlib may be unavailable
/Users/kyle/Github/swift-testing/.build/checkouts/swift-syntax/Sources/SwiftCompilerPlugin/CompilerPlugin.swift:103:19: error: cannot find 'dup' in scope
    let inputFD = dup(fileno(stdin))
                  ^~~
/Users/kyle/Github/swift-testing/.build/checkouts/swift-syntax/Sources/SwiftCompilerPlugin/CompilerPlugin.swift:117:20: error: cannot find 'dup' in scope
    let outputFD = dup(fileno(stdout))
                   ^~~
/Users/kyle/Github/swift-testing/.build/checkouts/swift-syntax/Sources/SwiftCompilerPlugin/CompilerPlugin.swift:124:11: error: cannot find 'dup2' in scope
    guard dup2(fileno(stderr), fileno(stdout)) >= 0 else {
```

## Context

I'm maintaining some library which supports WASI. After converting to swift-testing, the WASI CI is failing. I have to disable it for now.

## Priority

Low.

Before we add official WASI support in Swift Project. The priority is low here and I only open the issue for keep tracking the progress.

**Comment by Kyle-Ye** [comment] 2024-02-18 14:46
cc @kateinoigakukun in case you are interested for pushing this up.

**Comment by kateinoigakukun** [comment] 2024-02-18 14:55
https://github.com/apple/swift-package-manager/pull/7118 will unblock this

**Comment by grynspan** [comment] 2024-02-19 12:17
We'd love to support WASI/WASM! Are you able to build to a point where you can see failures in swift-testing yet, or are you blocked by the swift-syntax failures? (Our dependency on swift-syntax is limited to the compiler side of things, so we may be able to hack around the build failures if they cannot reasonably be solved.)

**Comment by MaxDesiatov** [comment] 2024-02-19 15:03
The failures are not caused by swift-syntax or the compiler, it's SwiftPM passing a wrong triple to the Swift Syntax build when compiling dependencies of macros. That was fixed in the PR linked above, but we may need to revert that until we resolve remaining issues with how triple arguments are passed for cross-compiled builds.

**Comment by grynspan** [comment] 2024-02-19 18:40
Thank you for the additional info, Max. 🙂 I said swift-syntax because the failures were reported against that package. I understand the nature of the failure here, and that the root cause is because SwiftPM is building our macro target and its dependencies for the target platform.

**Comment by Kyle-Ye** [comment] 2024-02-20 02:40
> The failures are not caused by swift-syntax or the compiler, it's SwiftPM passing a wrong triple to the Swift Syntax build when compiling dependencies of macros. That was fixed in the PR linked above, but we may need to revert that until we resolve remaining issues with how triple arguments are passed for cross-compiled builds.

Thanks for the tip. Would you mind cc me when the issue is eventually fixed to the nightly toolchain as I may not check the PRs on SwiftPM frequently?

**Comment by grynspan** [comment] 2024-02-23 16:41
As an administrative thing, I'm going to mark issues asking for new platform support as _enhancements_ rather than _bugs_. (Carry on!)

**Comment by kateinoigakukun** [comment] 2024-07-31 16:29
Closing as we added experimental support by https://github.com/apple/swift-testing/pull/584

**Closed by kateinoigakukun** 2024-07-31 16:29 UTC
Labels: enhancement, help wanted, wasi/wasm
