### ISSUE TITLE
Documentation on Swift Package Index returns a 404

### ISSUE THREAD

**Issue by polpielladev** [apple/swift-testing#483] opened 2024-06-13 19:58 UTC
### Description

Hi! 

I have noticed that the page on the Swift Package Index where Swift Testing's documentation is hosted is returning a 404 and wanted to raise it so that you're aware of the issue. 

https://github.com/apple/swift-testing/assets/24246926/97a27cb6-fdfb-4f53-aa85-9ac0495e3151

Please do let me know if there is anything I can do to help or if you want me to raise this issue in Swift Package Index's side.

### Steps to reproduce

1. Navigate to [swift-testing's documentation on Swift Package Index](https://swiftpackageindex.com/apple/swift-testing/main/documentation/testing)
2. The page 404s.

**Comment by squarefrog** [comment] 2024-06-13 22:12
For now, you can view the an older releases documentation here 

https://swiftpackageindex.com/apple/swift-testing/0.9.0/documentation/testing/temporarygettingstarted

**Comment by stmontgomery** [comment] 2024-06-13 22:17
Thank you, we're investigating

**Comment by stmontgomery** [comment] 2024-06-14 03:01
This appears to be a problem with SwiftPackageIndex itself, which is being investigated.

Duplicate of SwiftPackageIndex/SwiftPackageIndex-Server#3134

**Closed by stmontgomery** 2024-06-14 03:01 UTC
Labels: bug

**Comment by finestructure** [comment] 2024-06-14 08:27
The docs are back, sorry for the inconvenience!
