### ISSUE TITLE
Macro generates code that doesn't compile if `func` is on separate line

### ISSUE THREAD

**Issue by JetForMe** [apple/swift-testing#561] opened 2024-07-21 02:25 UTC
### Description

If you format your test function like this:

```swift
@Test
func
testModelType() { }
```

Then the generated code fails to compile, because the newline is included in the generated code:

```swift
    _ = try await ($s14SwiftTIFFTests03GeoB0V13testModelType4TestfMp_19functestModelType__fMu_.
                                                                                              ^ Expected member name following '.'
    	testModelType(), Testing.__requiringTry, Testing.__requiringAwait).0
```

### Expected behavior

Normal whitespace should have no effect on how a macro operates.

### Actual behavior

Whitespace affects the generated code badly

### Steps to reproduce

See above

### Swift & OS version (output of `swift --version ; uname -a`)

```
% swift --version ; uname -a
swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx14.0
Darwin eclipsem1.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

**Comment by stmontgomery** [comment] 2024-07-21 02:31
Duplicate of #520

**Closed** 2024-07-21 02:31 UTC
Labels: bug
